const carsData = [
  {
    id: 1,
    name: "Toyota Fortuner",
    brand: "Toyota",
    bodyType: "suv",
    use: ["family", "offroad", "towing"],
    price: 4500000,
    image: "https://images.unsplash.com/photo-1619767886645-0ae16581bf6b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dG95b3RhJTIwZm9ydHVuZXJ8ZW58MHx8MHx8fDA%3D",
    engine: "2.8L Diesel",
    power: "204 HP",
    torque: "500 Nm",
    transmission: "6-Speed Automatic",
    fuelType: "Diesel",
    seating: 7,
    mileage: "14 kmpl",
    safety: "5 Star",
    features: ["4WD", "Hill Descent Control", "Terrain Management", "Apple CarPlay", "Sunroof"],
    description: "The Toyota Fortuner is a robust, body-on-frame SUV built for tough terrains with legendary reliability."
  },
  {
    id: 2,
    name: "Maruti Swift",
    brand: "Maruti Suzuki",
    bodyType: "hatchback",
    use: ["family", "city"],
    price: 750000,
    image: "https://images.unsplash.com/photo-1699339395764-1c4f2717d271?q=80&w=1228&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    engine: "1.2L Petrol",
    power: "89 HP",
    torque: "113 Nm",
    transmission: "5-Speed Manual",
    fuelType: "Petrol",
    seating: 5,
    mileage: "23 kmpl",
    safety: "3 Star",
    features: ["Apple CarPlay", "Android Auto", "Automatic Climate Control", "Cruise Control"],
    description: "The Maruti Swift is India's best-selling hatchback, known for fun driving dynamics and fuel efficiency."
  },
  {
    id: 3,
    name: "Ford Ranger",
    brand: "Ford",
    bodyType: "pickup",
    use: ["work", "towing", "offroad"],
    price: 3800000,
    image: "https://images.unsplash.com/photo-1700943937372-12c2611b5af8?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    engine: "2.0L BiTurbo Diesel",
    power: "213 HP",
    torque: "500 Nm",
    transmission: "10-Speed Automatic",
    fuelType: "Diesel",
    seating: 5,
    mileage: "12 kmpl",
    safety: "5 Star",
    features: ["4WD", "Pro Power Onboard", "360° Camera", "Trail Control", "Ford Co-Pilot360"],
    description: "The Ford Ranger is a capable pickup truck ideal for heavy-duty work and adventurous off-roading."
  },
  {
    id: 4,
    name: "Tesla Model 3",
    brand: "Tesla",
    bodyType: "sedan",
    use: ["tech", "family", "city"],
    price: 5500000,
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400",
    engine: "Electric Motor",
    power: "350 HP",
    torque: "450 Nm",
    transmission: "Single Speed",
    fuelType: "Electric",
    seating: 5,
    mileage: "576 km range",
    safety: "5 Star",
    features: ["Autopilot", "15\" Touchscreen", "OTA Updates", "Supercharging", "Sentry Mode"],
    description: "The Tesla Model 3 is the most advanced electric sedan with cutting-edge autonomous driving tech."
  },
  {
    id: 5,
    name: "Hyundai Creta",
    brand: "Hyundai",
    bodyType: "suv",
    use: ["family", "city"],
    price: 1800000,
    image: "https://images.unsplash.com/photo-1748214547306-360d11024747?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8aHl1bmRhaSUyMGNyZXRhfGVufDB8fDB8fHww",
    engine: "1.5L Petrol",
    power: "115 HP",
    torque: "144 Nm",
    transmission: "CVT Automatic",
    fuelType: "Petrol",
    seating: 5,
    mileage: "17 kmpl",
    safety: "5 Star",
    features: ["Panoramic Sunroof", "BOSE Sound", "Ventilated Seats", "BlueLink Connected", "ADAS"],
    description: "The Hyundai Creta is a premium compact SUV offering luxury features at an accessible price."
  },
  {
    id: 6,
    name: "Mahindra Thar",
    brand: "Mahindra",
    bodyType: "suv",
    use: ["offroad", "family"],
    price: 1600000,
    image: "https://images.unsplash.com/photo-1710225358761-4f5891df657d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWFoaW5kcmElMjB0aGFyfGVufDB8fDB8fHww",
    engine: "2.2L mHawk Diesel",
    power: "130 HP",
    torque: "300 Nm",
    transmission: "6-Speed Manual",
    fuelType: "Diesel",
    seating: 4,
    mileage: "15 kmpl",
    safety: "4 Star",
    features: ["4WD", "Convertible Roof", "Adventure Statistics", "Waterproof Interior", "Rock Crawling Mode"],
    description: "The Mahindra Thar is India's iconic off-road vehicle built for extreme terrain adventures."
  },
  {
    id: 7,
    name: "Tata Ace",
    brand: "Tata",
    bodyType: "mini-truck",
    use: ["work", "towing"],
    price: 600000,
    image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=400  ",
    engine: "0.7L Diesel",
    power: "37 HP",
    torque: "95 Nm",
    transmission: "5-Speed Manual",
    fuelType: "Diesel",
    seating: 2,
    mileage: "20 kmpl",
    safety: "3 Star",
    features: ["High Payload", "Spacious Cabin", "Power Steering", "Low Maintenance"],
    description: "The Tata Ace is India's most popular mini-truck, trusted for last-mile commercial delivery."
  },
  {
    id: 8,
    name: "BMW 3 Series",
    brand: "BMW",
    bodyType: "sedan",
    use: ["tech", "family", "city"],
    price: 5800000,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400",
    engine: "2.0L TwinPower Turbo",
    power: "255 HP",
    torque: "400 Nm",
    transmission: "8-Speed Automatic",
    fuelType: "Petrol",
    seating: 5,
    mileage: "14 kmpl",
    safety: "5 Star",
    features: ["BMW iDrive", "Harman Kardon", "Adaptive Suspension", "Wireless CarPlay", "Parking Assistant"],
    description: "The BMW 3 Series defines the sports sedan segment with dynamic handling and premium luxury."
  },
  {
    id: 9,
    name: "Kia Carens",
    brand: "Kia",
    bodyType: "mpv",
    use: ["family", "towing"],
    price: 1400000,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSatufX6VigOuvhL6aZOSISYoP2E77vV-Mx4iIxGvA6KzpVoxa55YrXslNbz9CiSJb3p3FqSIttT05E-p_4kxwVC7TfXqLQC1rFKO3ZyXZ1&s=10",
    engine: "1.5L CRDi Diesel",
    power: "115 HP",
    torque: "250 Nm",
    transmission: "6-Speed Manual",
    fuelType: "Diesel",
    seating: 7,
    mileage: "21 kmpl",
    safety: "5 Star",
    features: ["Panoramic Display", "Bose Premium Sound", "ADAS Level 2", "Relaxation Seats", "Wireless Charging"],
    description: "The Kia Carens is a spacious and stylish MPV perfect for large families who value comfort."
  },
  {
    id: 10,
    name: "Volkswagen Polo",
    brand: "Volkswagen",
    bodyType: "hatchback",
    use: ["city", "family"],
    price: 1100000,
    image: "https://images.pexels.com/photos/14182396/pexels-photo-14182396.jpeg",
    engine: "1.0L TSI",
    power: "110 HP",
    torque: "175 Nm",
    transmission: "6-Speed Automatic",
    fuelType: "Petrol",
    seating: 5,
    mileage: "18 kmpl",
    safety: "4 Star",
    features: ["Virtual Cockpit", "Vienna Leather Seats", "Adaptive Cruise Control", "Lane Assist"],
    description: "The Volkswagen Polo is a refined European hatchback offering premium build quality in a compact package."
  },
  {
    id: 11,
    name: "Honda City",
    brand: "Honda",
    bodyType: "sedan",
    use: ["city", "family"],
    price: 1200000,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGzwia4Yl0YctMzSTVM_sujX0YQhBXSwnj-Q&s",
    engine: "1.5L i-VTEC",
    power: "129 HP",
    torque: "156 Nm",
    transmission: "CVT Automatic",
    fuelType: "Petrol",
    seating: 5,
    mileage: "16 kmpl",
    safety: "5 Star",
    features: ["Honda Sensing", "Honda CONNECT", "Adaptive Cruise Control", "Lane Keeping Assist"],
    description: "The Honda City is a compact sedan offering a perfect blend of style, comfort, and fuel efficiency."
  },
  {
    id: 12,
    name: "Renault Kwid",
    brand: "Renault",
    bodyType: "hatchback",
    use: ["city", "family"],
    price: 500000,
    image: "https://images.unsplash.com/photo-1700943937372-12c2611b5af8?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    engine: "0.8L SCe",
    power: "54 HP",
    torque: "72 Nm",
    transmission: "5-Speed Manual",
    fuelType: "Petrol",
    seating: 5,
    mileage: "22 kmpl",
    safety: "3 Star",
    features: ["MediaNAV Evolution", "Digital Instrument Cluster", "Rear Parking Sensors", "LED DRLs"],
    description: "The Renault Kwid is an affordable and stylish hatchback designed for urban mobility with a high ground clearance."
  },
{
    id: 13,
    name: "Audi Q5",
    brand: "Audi",
    bodyType: "suv",
    use: ["family", "city"],
    price: 4500000,
    image: "https://imgs.search.brave.com/09WaTbuR28QQeyfWAJlYr2PXy7bF_h0tRDToCLLdmxE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4t/czMuYXV0b2Nhcmlu/ZGlhLmNvbS9BdWRp/L3E1L0dUXzA4MDM2/LkpQRz93PTI1NiZx/PTc1",
    engine: "2.0L TFSI",
    power: "255 HP",
    torque: "370 Nm",
    transmission: "8-Speed Automatic",
    fuelType: "Petrol",
    seating: 5,
    mileage: "15 kmpl",
    safety: "5 Star",
    features: ["Virtual Cockpit", "Bose Premium Sound", "Adaptive Suspension", "Wireless CarPlay", "Parking Assistant"],
    description: "The Audi Q5 is a luxury SUV that combines sporty performance with refined comfort and advanced technology."
  },
{
  id: 14,
  name: "Toyota Innova Crysta",
  brand: "Toyota",
  bodyType: "mpv",
  use: ["family", "touring", "towing"],
  price: 2500000,
  image: "https://imgs.search.brave.com/m-7eGzPPcn9DVtr5Qp7oxQAFqAKV60gcblT4Twkm6UI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvMTg5/NTA0MC5qcGc",
  engine: "2.4L Diesel",
  power: "150 HP",
  torque: "343 Nm",
  transmission: "6-Speed Manual",
  fuelType: "Diesel",
  seating: 7,
  mileage: "13 kmpl",
  safety: "5 Star",
  features: ["Captain Seats", "Rear AC Vents", "Touchscreen", "Cruise Control", "Dual Airbags"],
  description: "The Toyota Innova Crysta is a premium MPV known for reliability, comfort, and long-distance travel."
},
{
  id: 15,
  name: "Hyundai Venue",
  brand: "Hyundai",
  bodyType: "suv",
  use: ["city", "family"],
  price: 1200000,
  image: "https://imgs.search.brave.com/vyJaV3kAMRp3VRjrQiuLI32Wrjb6wjYpIoq-N_6Nxmw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvMjUz/MDAwOS5qcGc",
  engine: "1.0L Turbo Petrol",
  power: "120 HP",
  torque: "172 Nm",
  transmission: "7-Speed DCT",
  fuelType: "Petrol",
  seating: 5,
  mileage: "18 kmpl",
  safety: "4 Star",
  features: ["Bluelink", "Sunroof", "Wireless Charging", "Cruise Control", "LED Headlamps"],
  description: "The Hyundai Venue is a compact SUV designed for urban driving with premium features and turbo performance."
},
{
  id: 16,
  name: "Kia Sonet",
  brand: "Kia",
  bodyType: "suv",
  use: ["city", "family"],
  price: 1250000,
  image: "https://imgs.search.brave.com/lGLf4mNFowXlbR5q280kpFXz10ll6-hYJoDppi2QQeg/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvNzgx/Nzg1OS5qcGc",
  engine: "1.5L Diesel",
  power: "115 HP",
  torque: "250 Nm",
  transmission: "6-Speed Automatic",
  fuelType: "Diesel",
  seating: 5,
  mileage: "19 kmpl",
  safety: "4 Star",
  features: ["Ventilated Seats", "Touchscreen", "Bose Audio", "Cruise Control", "Connected Car Tech"],
  description: "The Kia Sonet is a stylish compact SUV with premium interiors and great fuel economy."
},
{
  id: 17,
  name: "Tata Safari",
  brand: "Tata",
  bodyType: "suv",
  use: ["family", "highway"],
  price: 2900000,
  image: "https://imgs.search.brave.com/-o8ma2GsF0xorNtkbliqdk6uZd8mUOMiQLwuiLTULVk/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWdk/LmFlcGxjZG4uY29t/LzY2NHgzNzQvbi9j/dy9lYy80MDAyNy9z/YWZhcmktZXh0ZXJp/b3ItbGVmdC1yZWFy/LXRocmVlLXF1YXJ0/ZXItMi5qcGVnP3E9/ODA",
  engine: "2.0L Diesel",
  power: "170 HP",
  torque: "350 Nm",
  transmission: "6-Speed Automatic",
  fuelType: "Diesel",
  seating: 7,
  mileage: "14 kmpl",
  safety: "5 Star",
  features: ["Panoramic Sunroof", "ADAS", "Captain Seats", "Touchscreen", "Premium Audio"],
  description: "The Tata Safari is a premium 7-seater SUV built for comfort, power, and long highway drives."
},
{
  id: 18,
  name: "Kushaq",
  brand: "Skoda",
  bodyType: "suv",
  use: ["family", "city"],
  price: 1700000,
  image: "https://imgs.search.brave.com/-T5yUSBi0FKa52oTH8xhxdqhS3Tq4VOag68G7Jr1880/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDEyMTU5/NDc0LmpwZw",
  engine: "1.5L TSI Turbo",
  power: "150 HP",
  torque: "250 Nm",
  transmission: "7-Speed DSG",
  fuelType: "Petrol",
  seating: 5,
  mileage: "17 kmpl",
  safety: "5 Star",
  features: ["Ventilated Seats", "Sunroof", "Touchscreen", "ESC", "Wireless Charging"],
  description: "The Skoda Kushaq is a European compact SUV offering excellent build quality and turbo performance."
},
{
  id: 19,
  name: "Volkswagen Taigun",
  brand: "Volkswagen",
  bodyType: "suv",
  use: ["family", "city"],
  price: 1750000,
  image: "https://imgs.search.brave.com/k_ymjRDbpyAntF554XFOAeSaS3AOX8pd6rIB54_MZIQ/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDk1MTU0/MzEuanBn",
  engine: "1.5L TSI Turbo",
  power: "150 HP",
  torque: "250 Nm",
  transmission: "7-Speed DSG",
  fuelType: "Petrol",
  seating: 5,
  mileage: "18 kmpl",
  safety: "5 Star",
  features: ["Digital Cockpit", "Sunroof", "ESC", "Wireless CarPlay", "Cruise Control"],
  description: "The Volkswagen Taigun is a sporty SUV with German engineering and premium interiors."
},
{
  id: 20,
  name: "Toyota Camry",
  brand: "Toyota",
  bodyType: "sedan",
  use: ["luxury", "family", "city"],
  price: 4800000,
  image: "https://imgs.search.brave.com/BllvGt4wlGLQmH-dRD4qMf4g9XHgL6Xdh8u3qI_oiaA/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvODE2/MTczMS5wbmc",
  engine: "2.5L Hybrid",
  power: "218 HP",
  torque: "221 Nm",
  transmission: "e-CVT",
  fuelType: "Hybrid",
  seating: 5,
  mileage: "19 kmpl",
  safety: "5 Star",
  features: ["Leather Seats", "Sunroof", "Hybrid Drive", "Cruise Control", "Premium Audio"],
  description: "The Toyota Camry is a luxury hybrid sedan offering comfort, smooth ride, and excellent efficiency."
},
{
  id: 21,
  name: "Honda Civic",
  brand: "Honda",
  bodyType: "sedan",
  use: ["city", "family"],
  price: 2200000,
  image: "https://imgs.search.brave.com/gGim-h1WnN63EuYOWtrSkXyKIFW4vb4uWSQ3MnFyOdo/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvMTY1/Njc0Mi5qcGc",
  engine: "1.5L Turbo Petrol",
  power: "176 HP",
  torque: "240 Nm",
  transmission: "CVT Automatic",
  fuelType: "Petrol",
  seating: 5,
  mileage: "16 kmpl",
  safety: "5 Star",
  features: ["Touchscreen", "Cruise Control", "Lane Assist", "Sunroof", "Premium Interiors"],
  description: "The Honda Civic is a sporty sedan offering premium comfort and refined turbo performance."
},
{
  id: 22,
  name: "Ford Endeavour",
  brand: "Ford",
  bodyType: "suv",
  use: ["offroad", "family", "towing"],
  price: 4200000,
  image: "https://imgs.search.brave.com/Eyg6xEF_LKyk2zVUcnC0oi8x2MWLSgdGymdOQOHwNWU/rs:fit:0:180:1:0/g:ce/aHR0cDovL3d3dy5q/c3Bmb3JkLmNvbS9m/b3JkLWVuZGVhdm91/ci9pbWFnZXMvYmFu/bmVyMS5qcGc",
  engine: "2.0L Diesel",
  power: "210 HP",
  torque: "500 Nm",
  transmission: "10-Speed Automatic",
  fuelType: "Diesel",
  seating: 7,
  mileage: "12 kmpl",
  safety: "5 Star",
  features: ["4WD", "Terrain Modes", "Sunroof", "Cruise Control", "Hill Descent Control"],
  description: "The Ford Endeavour is a rugged SUV designed for off-road adventures and long highway travel."
},
{
  id: 23,
  name: "Jeep Wrangler",
  brand: "Jeep",
  bodyType: "suv",
  use: ["offroad", "adventure"],
  price: 6500000,
  image: "https://imgs.search.brave.com/e3AS2QrtIINGcjnMRvoheCM6jVXJS1maCDG_a0SIv-o/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWdk/LmFlcGxjZG4uY29t/LzM3MHgyMDgvbi9j/dy9lYy8xNzQ5NzUv/d3JhbmdsZXItZXh0/ZXJpb3ItY2xvc2Vk/LWhvb2QtYm9ubmV0/LmpwZWc_aXNpZz0w/JnE9ODA",
  engine: "2.0L Turbo Petrol",
  power: "270 HP",
  torque: "400 Nm",
  transmission: "8-Speed Automatic",
  fuelType: "Petrol",
  seating: 5,
  mileage: "10 kmpl",
  safety: "5 Star",
  features: ["4x4", "Removable Roof", "Offroad Tyres", "Terrain Modes", "Hill Hold Assist"],
  description: "The Jeep Wrangler is a legendary off-road SUV built for extreme adventure and rugged terrain."
},
{
  id: 24,
  name: "BMW M4",
  brand: "BMW",
  bodyType: "sports",
  use: ["performance", "luxury"],
  price: 14000000,
  image: "https://imgs.search.brave.com/ehhuIgCIvGzZwgbQJs99yZdC9X4BGY8CUhkcT10AEiE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jZG4t/czMuYXV0b2Nhcmlu/ZGlhLmNvbS9sZWdh/Y3kvY2RuaS9tbXZf/aW1hZ2VzL2NvbG9y/cy8yMDI1MDcxNzEy/NTgyMV9CTVdfTTRf/U2FvX1Bhb2xvX1ll/bGxvd1sxXS5wbmc_/dz02NDAmcT03NQ",
  engine: "3.0L Twin Turbo",
  power: "503 HP",
  torque: "650 Nm",
  transmission: "8-Speed Automatic",
  fuelType: "Petrol",
  seating: 4,
  mileage: "9 kmpl",
  safety: "5 Star",
  features: ["Launch Control", "Sport Exhaust", "M Drive Modes", "Carbon Roof", "Track Mode"],
  description: "The BMW M4 is a high-performance sports coupe delivering extreme power and aggressive handling."
},
{
  id: 25,
  name: "Audi RS5",
  brand: "Audi",
  bodyType: "sports",
  use: ["performance", "luxury"],
  price: 12000000,
  image: "https://imgs.search.brave.com/TgcpdpN-c0vF8RLJckkLO6zqJhn6V9Wore-i_TvlSW8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuZHJpdmVzcGFy/ay5jb20vcGgtYmln/LzIwMjEvMDgvMjAy/MS1hdWRpLXJzNS1z/cG9ydGJhY2stMTEu/anBn",
  engine: "2.9L Twin Turbo V6",
  power: "444 HP",
  torque: "600 Nm",
  transmission: "8-Speed Automatic",
  fuelType: "Petrol",
  seating: 4,
  mileage: "10 kmpl",
  safety: "5 Star",
  features: ["Quattro AWD", "Launch Control", "Sport Suspension", "Virtual Cockpit", "Premium Audio"],
  description: "The Audi RS5 is a luxury performance coupe with aggressive styling and powerful turbo acceleration."
},
{
 id: 26,
  name:"Maruti Alto",
  brand: "Maruti Suzuki",
  bodyType: "hatchback",
  use: ["city", "family"],
  price: 350000,
  image: "https://imgs.search.brave.com/wg3svZ-FhNl7BeE1gsSnsoaT3AR5r86z6XvWNkpz6vs/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/Y2FyYW5kYmlrZS5j/b20vX25leHQvaW1h/Z2U_dXJsPWh0dHBz/Oi8vaW1hZ2VzLmNh/cmFuZGJpa2UuY29t/L2Nhci1pbWFnZXMv/YmlnL21hcnV0aS1z/dXp1a2kvYWx0by9t/YXJ1dGktc3V6dWtp/LWFsdG8uanBnP3Y9/MV8xJnc9NjQwJnE9/OTA",
  engine: "1.2L Petrol",
  power: "89 HP",
  torque: "113 Nm",
  transmission: "CVT Automatic",
  fuelType: "Petrol",
  seating: 5,
  mileage: "22 kmpl",
  safety: "3 Star",
  features: ["Touchscreen", "Heads-Up Display", "Cruise Control", "ABS", "Dual Airbags"],
  description: "The Maruti Alto is a compact hatchback known for its affordability and fuel efficiency."
},
{
 id: 27,
  name: "Maruti WagonR",
  brand: "Maruti Suzuki",
  bodyType: "hatchback",
  use: ["city", "family"],
  price: 550000,
  image: "https://imgs.search.brave.com/ZfmiKw70aZEwuYd_qiav4sCsEdPeRytk0IC0AKQCbOA/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDExMzI4/NTgwLmpwZw",
  engine: "1.2L Petrol",
  power: "89 HP",
  torque: "113 Nm",
  transmission: "CVT Automatic",
  fuelType: "Petrol",
  seating: 5,
  mileage: "22 kmpl",
  safety: "3 Star",
  features: ["Touchscreen", "Heads-Up Display", "Cruise Control", "ABS", "Dual Airbags"],
  description: "The Maruti WagonR is a compact hatchback known for its affordability and fuel efficiency."
},
{
  id: 28,
  name: "Maruti Baleno",
  brand: "Maruti Suzuki",
  bodyType: "hatchback",
  use: ["city", "family"],
  price: 900000,
  image: "https://imgs.search.brave.com/mfXRrS5a4ZWLqFLUW3VxUWRDcxn-ABoJ4HKv6goEEak/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jZG4t/czMuYXV0b2Nhcmlu/ZGlhLmNvbS9sZWdh/Y3kvY2RuaS9SZXZp/ZXdzL01hcnV0aS1C/YWxlbm8tMjAyMi1u/b3NlLmpwZz93PTcw/MCZjPTA",
  engine: "1.2L Petrol",
  power: "89 HP",
  torque: "113 Nm",
  transmission: "CVT Automatic",
  fuelType: "Petrol",
  seating: 5,
  mileage: "22 kmpl",
  safety: "3 Star",
  features: ["Touchscreen", "Heads-Up Display", "Cruise Control", "ABS", "Dual Airbags"],
  description: "The Maruti Baleno is a premium hatchback popular in India for its spacious cabin and fuel efficiency."
},
{
  id: 29,
  name: "Maruti Dzire",
  brand: "Maruti Suzuki",
  bodyType: "sedan",
  use: ["city", "family"],
  price: 950000,
  image: "https://imgs.search.brave.com/M5Vo6YryfdXQ-kuIoKbc6ZItcbZquyREtlYE5et7bXE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jZG4t/czMuYXV0b2Nhcmlu/ZGlhLmNvbS9sZWdh/Y3kvY2RuaS9FeHRy/YUltYWdlcy8yMDI1/MDgxMTA4MjQ0OF9N/YXJ1dGlfU3V6dWtp/X0R6aXJlX0Zyb250/X1F1YXJ0ZXJfU3Rh/dGljLmpwZz93PTY0/MCZxPTc1",
  engine: "1.2L Petrol",
  power: "82 HP",
  torque: "113 Nm",
  transmission: "5-Speed Manual / AMT",
  fuelType: "Petrol",
  seating: 5,
  mileage: "24 kmpl",
  safety: "4 Star",
  features: ["Rear Camera", "Touchscreen", "Cruise Control", "ABS", "Dual Airbags"],
  description: "The Maruti Dzire is one of India's best-selling compact sedans, known for comfort and mileage."
},
{
  id: 30,
  name: "Maruti Ertiga",
  brand: "Maruti Suzuki",
  bodyType: "mpv",
  use: ["family", "touring"],
  price: 1150000,
  image: "https://imgs.search.brave.com/NSENnB4Uw7w93myevaZj1Tc5cd4FuesIfLvc_an-Gt0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWdk/LWN0LmFlcGxjZG4u/Y29tLzEwNTZ4NjYw/L24vY3cvZWMvMTE1/Nzc3L2VydGlnYS1l/eHRlcmlvci1mcm9u/dC12aWV3LmpwZWc_/aXNpZz0wJnE9ODA",
  engine: "1.5L Petrol",
  power: "103 HP",
  torque: "138 Nm",
  transmission: "6-Speed Automatic",
  fuelType: "Petrol",
  seating: 7,
  mileage: "20 kmpl",
  safety: "4 Star",
  features: ["Rear AC Vents", "Touchscreen", "ABS", "Airbags", "Captain Seats Option"],
  description: "The Maruti Ertiga is a practical 7-seater MPV ideal for Indian families and long drives."
},
{
  id: 31,
  name: "Tata Nexon",
  brand: "Tata",
  bodyType: "suv",
  use: ["city", "family"],
  price: 1400000,
  image: "https://imgs.search.brave.com/wIfJVxMM5SjzJ6oPZIiEvxoPilT_lRu0GVgcEU02MHQ/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWdk/LWN0LmFlcGxjZG4u/Y29tLzEwNTZ4NjYw/L24vY3cvZWMvMTg5/ODc1L3RhdGEtbmV4/b24tbGVmdC1mcm9u/dC10aHJlZS1xdWFy/dGVyOC5qcGVnP2lz/aWc9MCZ3bT00JnE9/ODA",
  engine: "1.2L Turbo Petrol",
  power: "120 HP",
  torque: "170 Nm",
  transmission: "6-Speed Manual",
  fuelType: "Petrol",
  seating: 5,
  mileage: "17 kmpl",
  safety: "5 Star",
  features: ["Sunroof", "ESP", "Cruise Control", "Touchscreen", "Connected Car Tech"],
  description: "The Tata Nexon is a compact SUV known for its 5-star safety rating and stylish design."
},
{
  id: 32,
  name: "Tata Punch",
  brand: "Tata",
  bodyType: "suv",
  use: ["city", "family"],
  price: 850000,
  image: "https://imgs.search.brave.com/P3248ZXO3g4KQaWM-tY3bqQqGPA-OGZQf7VVtoB_sgY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDEwMzYx/Nzg4LmpwZw",
  engine: "1.2L Petrol",
  power: "86 HP",
  torque: "113 Nm",
  transmission: "5-Speed Manual / AMT",
  fuelType: "Petrol",
  seating: 5,
  mileage: "20 kmpl",
  safety: "5 Star",
  features: ["Touchscreen", "Hill Hold Assist", "ABS", "Airbags", "Rear Parking Sensors"],
  description: "The Tata Punch is a micro SUV popular in India for its strong build quality and safety."
},
{
  id: 33,
  name: "Mahindra XUV700",
  brand: "Mahindra",
  bodyType: "suv",
  use: ["family", "highway", "tech"],
  price: 3200000,
  image: "https://imgs.search.brave.com/ZNyXBd2Z3NyoLqIR6w06RxmnyuKbEnqfWZt1o5IOLu4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvODY2/NTUwMy5qcGc",
  engine: "2.2L Diesel",
  power: "185 HP",
  torque: "450 Nm",
  transmission: "6-Speed Automatic",
  fuelType: "Diesel",
  seating: 7,
  mileage: "15 kmpl",
  safety: "5 Star",
  features: ["ADAS", "Panoramic Sunroof", "Digital Cockpit", "360 Camera", "Premium Audio"],
  description: "The Mahindra XUV700 is a feature-packed SUV offering powerful performance and modern technology."
},
{
  id: 34,
  name: "Mahindra Bolero",
  brand: "Mahindra",
  bodyType: "suv",
  use: ["family", "offroad"],
  price: 900000,
  image: "https://imgs.search.brave.com/v56hCNbOKytfhVaQPqcjV-OIU1ZXQciQDaVo4AwPLWA/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvODI3/ODE5NC5qcGc",
  engine: "1.5L Diesel",
  power: "75 HP",
  torque: "210 Nm",
  transmission: "5-Speed Manual",
  fuelType: "Diesel",
  seating: 7,
  mileage: "18 kmpl",
  safety: "4 Star",
  features: ["4WD", "High Ground Clearance", "Rugged Build", "Rear AC Vents", "Touchscreen"],
  description: "The Mahindra Bolero is a rugged SUV built for Indian roads, offering durability and off-road capability."
},
{
 id:35,
  name:"Honda Elevate",
  brand: "Honda",
  bodyType: "suv",  
  use: ["family", "city"],
  price: 2500000,
  image: "https://imgs.search.brave.com/g9SBYQTC55niDz_5sToHF74Tmc_9kV8SjD-KQuBP3nY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/Y2FyYW5kYmlrZS5j/b20vX25leHQvaW1h/Z2U_dXJsPWh0dHBz/Oi8vaW1hZ2VzLmNh/cmFuZGJpa2UuY29t/L2Nhci1pbWFnZXMv/Z2FsbGVyeS9ob25k/YS9lbGV2YXRlL2V4/dGVyaW9yL2hvbmRh/LWVsZXZhdGVfMy5q/cGc_dj0xNzUyOTIx/MDc1Jnc9NjQwJnE9/OTA",
  engine: "1.5L Turbo Petrol",
  power: "120 HP",
  torque: "145 Nm",
  transmission: "CVT Automatic",
  fuelType: "Petrol",
  seating: 5,
  mileage: "16 kmpl",
  safety: "5 Star",
  features: ["Honda Sensing", "Panoramic Sunroof", "Touchscreen", "Cruise Control", "Wireless CarPlay"],
  description: "The Honda Elevate is a stylish compact SUV offering modern features and efficient performance for urban families."
},
{
  id: 36,
  name: "Kia Seltos",
  brand: "Kia",
  bodyType: "suv",
  use: ["family", "city"],
  price: 2000000,
  image: "https://imgs.search.brave.com/JVeqbQuzyqry18oZ3I5XqqB_0tgA-FkuguFCfzh2j9E/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXQuY29t/L3cvZnVsbC85Lzkv/My8xNjY4MTYxLTE5/MjB4MTA4MC1kZXNr/dG9wLTEwODBwLWtp/YS1zZWx0b3MtYmFj/a2dyb3VuZC1pbWFn/ZS5qcGc",
  engine: "1.5L Petrol",
  power: "115 HP",
  torque: "144 Nm",
  transmission: "CVT Automatic",
  fuelType: "Petrol",
  seating: 5,
  mileage: "17 kmpl",
  safety: "5 Star",
  features: ["Panoramic Sunroof", "Ventilated Seats", "ADAS", "Premium Audio", "Wireless CarPlay"],
  description: "The Kia Seltos is a popular premium SUV in India with feature-rich interiors and strong road presence."
},
{
  id: 37,
  name: "Renault Duster",
  brand: "Renault",
  bodyType: "suv",
  use: ["family", "offroad"],
  price: 1200000,
  image: "https://imgs.search.brave.com/fzTfKxTCJyCwfgqEgPnT4ERDMj1w1GuIN9f-xEbkatQ/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDcwNjEy/MTIuanBn",
  engine: "1.5L Diesel",
  power: "110 HP",
  torque: "260 Nm",
  transmission: "6-Speed Manual",
  fuelType: "Diesel",
  seating: 5,
  mileage: "19 kmpl",
  safety: "4 Star",
  features: ["4WD", "High Ground Clearance", "Rugged Build", "Rear AC Vents", "Touchscreen"],
  description: "The Renault Duster is a rugged SUV offering strong performance and off-road capability at an affordable price."
},
{
  id: 38,
  name: "Renault Triber",
  brand: "Renault",
  bodyType: "mpv",
  use: ["family", "city"],
  price: 850000,
  image: "https://imgs.search.brave.com/rg6rL5a6x-2smyNR5R68ih-aR5r94twrjY5iCmllV9c/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDk2MDE0/NzkuanBn",
  engine: "1.0L Petrol",
  power: "72 HP",
  torque: "96 Nm",
  transmission: "5-Speed Manual / AMT",
  fuelType: "Petrol",
  seating: 7,
  mileage: "19 kmpl",
  safety: "4 Star",
  features: ["Modular Seating", "Touchscreen", "ABS", "Airbags", "Rear Parking Sensors"],
  description: "The Renault Triber is a budget-friendly 7-seater MPV suitable for Indian families."
},
{
  id: 39,
  name: "MG Hector",
  brand: "MG",
  bodyType: "suv",
  use: ["family", "city"],
  price: 2200000,
  image: "https://imgs.search.brave.com/NkeWBVi1lbWch7HO4ew2NpotC1zpUN8xz0IpwP_29F8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDg3MjQ5/MjEuanBn",
  engine: "1.5L Turbo Petrol",
  power: "143 HP",
  torque: "250 Nm",
  transmission: "CVT Automatic",
  fuelType: "Petrol",
  seating: 5,
  mileage: "14 kmpl",
  safety: "5 Star",
  features: ["Panoramic Sunroof", "Large Touchscreen", "Connected Car Tech", "Premium Audio", "ADAS"],
  description: "The MG Hector is a premium SUV in India offering modern tech and a spacious cabin."
}

];